name: deferred_loading_example
version: 0.0.1
description: An example of deferred library loading in Dart.
dependencies:
  browser: any
  dart_to_js_script_rewriter: "^1.0.0"
  react: "^0.8.2"
  source_maps: ^0.10.1
environment:
  sdk: ">=1.9.0 <2.0.0"

transformers:
- dart_to_js_script_rewriter
- $dart2js:
    sourceMaps: true